# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3173320ac409da817cdc47b9daa531927d0a1118659f6029c111e9a265986f95a1418203b6bdca1128daf7860eefcf15c9344490e0033ac61acfc7dd53449ff9

test:
  secret_key_base: a06e6ecdbc22057a343cd56dd54114baee6a704d614ae8dce3f5c92d1934e769e8d9aa2f850498346badde0c0a2e3cde912fdaa5a14989709ad87511fb5b9309

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
